version: '3.9'

services:
  app:
    build:
      context: ./mynextjs
    ports:
      - "3000:3000"
    command: sh -c "sleep 10 && npm run dev"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: exampledb
    depends_on:
      - db
    volumes:
      - ./mynextjs:/app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: